services:
  accounts:
    image: "zunaidansari/accounts:v4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1000m
    networks:
      - yourbank
  loans:
    image: "zunaidansari/loans:v4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 1000m
    networks:
      - yourbank
  cards:
    image: "zunaidansari/cards:v4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1000m
    networks:
      - yourbank
networks:
  yourbank:
    driver: "bridge"