spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #  active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/zunaidansari/yourbank-config.git"
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
      # native:
      #   search-locations: "file:///D://config"
      #   search-locations: "classpath:/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


encrypt:
  key: "4HACIW4295KEUNSPQSMC913"
server:
  port: 8071